pipeline {
   agent any
   environment {
      Project_Dir = "02-single-server-deployment"
      Server_IP = credentials('prod_server_ip')
   }
   stages{
      stage('Checkout') {
         steps{
            git url: "https://github.com/gsdash12/course-jenkins-project.git", branch: 'main'
            sh 'ls -ltr'
         }
      }
      stage('Setup') {
         steps{
            sh '''
                cd "$Project_Dir"
                python3 -m venv venv
                . venv/bin/activate
                ./venv/bin/pip install --upgrade pip
                ./venv/bin/pip install -r requirements.txt
            '''   
         }
      }
      stage('Test') {
         steps{
            sh '''
                cd "$Project_Dir"
                . venv/bin/activate
                ./venv/bin/python -m pytest
            '''       
         }
      }
      stage('Package Code') {
         steps{
            sh '''
               cd "Project_Dir"
                "zip -r myapp.zip ./* -x '**.git**'"
                'ls -lart"
            '''
         }
      }
      stage('Deployment') {
         steps{
            echo 'hello world'
         }

      }
   }
}
