pipeline {
   agent any
   environment {
      Server_IP = credentials('prod_server_ip')
   }
   stages{
      stage('Checkout') {
         steps{
            git url: "https://github.com/gsdash12/course-jenkins-project.git", branch: 'main'
            sh 'ls -ltr'
         }
      }
      stage('Setup') {
         steps{
            sh 'python3 -m venv venv'
            sh 'source venv/bin/activate'
            sh 'pip install -r requirements.txt'
         }
      }
      stage('Tets') {
         steps{
            sh 'pytest'
         }
      }
      stage('Package Code') {
         steps{
            sh "zip -r myapp.zip ./* -x '**.git**'"
            sh 'ls -lart'
         }
      }
      stage('Deployment') {
         steps{
            echo 'hello world'
         }

      }
   }
}
