pipeline {
    agent any
    environment {
        Project_DIR = "04-docker"
        IMAGE_NAME = "gsdash12/docker_project"
        IMAGE_TAG = "${IMAGE_NAME}:${env.BUILD_NUMBER}"
    }
    stages {
        stage('checkout') {
            steps {
                git url: 'https://github.com/gsdash12/course-jenkins-project', branch: 'main'
                sh 'ls -ltr'
            }
        }
        stage('setup') {
            steps {
                sh '''
                    cd "${Project_DIR}"
                    python3.12 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''
                    cd "${Project_DIR}"
                    . venv/bin/activate -m pytest
                '''
            }
        }
        stage('login to dockerhub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-creds', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh '''
                        echo "${PASSWORD}" | docker login -u "${USERNAME}" --password-stdin
                        echo "logged in succesfully"
                    '''
                }
            }
        }
        stage('Docker Build') {
            steps {
                sh '''
                    cd "${Project_DIR}"
                    docker build -t "${IMAGE_TAG}" .
                    echo " Docker Image built Successfully "
                    docker image ls
                '''
            }
        }
    }
}